# Python Programming Basic Assignment_8

### 1. Write a Python Program to Add Two Matrices?
Ans:

In [1]:
import numpy as np
def matAdd(list_of_matrix):
    #Checking all the matrices are same in size
    if all(i.shape == list_of_matrix[0].shape for i in list_of_matrix):
        
        sum = np.zeros(list_of_matrix[0].shape)
        for i in list_of_matrix:
            #if list_of_matrix[i].shape == list_of_matrix[i+1].shape:
            sum = np.add(sum,i)
        return sum
    else:
        return "Shape of all the element is not same"

In [2]:
a = np.array([[1,2],[2,4]])
b = np.array([[4,2],[3,2]])
c = np.array([[1,2], [4,3]])

In [3]:
matAdd([a,b,c])

array([[6., 6.],
       [9., 9.]])

### 2. Write a Python Program to Multiply Two Matrices?
Ans:

In [4]:
import numpy as np
def matMul(list_of_matrix):
    if all(i.shape == list_of_matrix[0].shape for i in list_of_matrix):
        result = np.ones(list_of_matrix[0].shape)
        for i in list_of_matrix:
            result = np.matmul(result, i)
        return result

In [5]:
arr_1 = np.array([[1,2],[2,3],[4,5]])
arr_2 = np.array([[1,2,3],[4,3,2]])

In [6]:
np.matmul(arr_1, arr_2)

array([[ 9,  8,  7],
       [14, 13, 12],
       [24, 23, 22]])

### 3. Write a Python Program to Transpose a Matrix?
Ans:

In [7]:
def matrixTranspose(input_array):
    return np.transpose(input_array)

In [8]:
matrixTranspose(arr_2)

array([[1, 4],
       [2, 3],
       [3, 2]])

### 4. Write a Python Program to Sort Words in Alphabetic Order?
Ans:

In [9]:
def wordSorting(input_word_list, a_to_z = False):
    return sorted(input_word_list, reverse= a_to_z)

In [10]:
a = ["cat", "mouse", "dog", "zebra", "yak"]

In [11]:
wordSorting(a)

['cat', 'dog', 'mouse', 'yak', 'zebra']

In [12]:
wordSorting(a, a_to_z=True)

['zebra', 'yak', 'mouse', 'dog', 'cat']

### 5. Write a Python Program to Remove Punctuation From a String?
Ans:

In [13]:
def stringCleaning(input_string):
    removing_char = "[]{};:''<>?/|\!@#$%^&*-=_+"
    for i in input_string:
        if i in removing_char:
            input_string  = input_string.replace(i, "")
    return input_string

In [14]:
string = "What is your name?"
stringCleaning(string)

'What is your name'